version: 2.1
aliases:
  - &docker-node-lts
    - image: circleci/node:lts
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    macos:
      xcode: 11.3.0
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: xcodebuild test -scheme circleci-demo-macos
      - run:
          name: Build Application
          command: xcodebuild
      - run:
          name: Compress app for storage
          command: zip -r app.zip build/Release/circleci-demo-macos.app
      - store_artifacts:
          path: app.zip
          destination: app
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: curl https://install.meteor.com/ | sh
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
    lint:
      jobs:
        - lint